apiVersion: v1
kind: Service
metadata:
  name: {{ include "heart-disease-api.fullname" . }}
  labels:
    {{- include "heart-disease-api.labels" . | nindent 4 }}
  {{- if and .Values.metrics.enabled .Values.metrics.path .Values.metrics.port }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: {{ .Values.metrics.path | quote }}
    prometheus.io/port: {{ .Values.service.port | quote }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "heart-disease-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
