data:
  raw_path: "data/raw/heart_disease.csv"
  processed_path: "data/processed/heart_disease_clean.csv"

eda:
  figures_path: "reports/figures"

schema:
  target: "target"

preprocessing:
  categorical_features:
    - sex
    - cp
    - fbs
    - restecg
    - exang
    - slope
    - thal

  numerical_features:
    - age
    - trestbps
    - chol
    - thalach
    - oldpeak
    - ca
